//
// Created by felip on 17/05/2026.
//

#ifndef PROTECTOEST_JUEGODELDETECTIVE__UBICACION_H
#define PROTECTOEST_JUEGODELDETECTIVE__UBICACION_H


class Ubicacion {
};


#endif //PROTECTOEST_JUEGODELDETECTIVE__UBICACION_H